- clean: [ '~' ]

- create:
  - ~/.config
  - ~/.tmux

- link:
    ~/.tmux.conf: tmux.conf
    ~/.config/nvim: nvim
    ~/.zprezto: zprezto
    ~/.zprezto/runcoms/zlogin .zlogin
    ~/.zprezto/runcoms/zlogout .zlogout
    ~/.zprezto/runcoms/zpreztorc .zpreztorc
    ~/.zprezto/runcoms/zprofile .zprofile
    ~/.zprezto/runcoms/zshenv .zshenv
    ~/.zprezto/runcoms/zshrc .zshrc
    ~/.ideavimrc: ideavimrc
    ~/.tmux/start.sh: tmux/start.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [fc-cache -fv, Installing fonts]
