- clean: [ '~' ]

- create:
  - ~/.config
  - ~/.tmux

- link:
    ~/.tmux.conf: tmux.conf
    ~/.config/nvim: nvim
    ~/.zprezto: zprezto
    ~/.ideavimrc: ideavimrc
    ~/.tmux/start.sh: tmux/start.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [fc-cache -fv, Installing fonts]
