- clean: [ '~' ]

- create:
  - ~/.config
  - ~/.tmux

- link:
    ~/.tmux.conf: tmux.conf
    ~/.config/nvim: nvim
    ~/.config/atuin: atuin
    ~/.zprezto: zprezto
    ~/.zlogin: zprezto/runcoms/zlogin
    ~/.zlogout: zprezto/runcoms/zlogout
    ~/.zpreztorc: zprezto/runcoms/zpreztorc 
    ~/.zprofile: zprezto/runcoms/zprofile
    ~/.zshenv: zprezto/runcoms/zshenv
    ~/.zshrc: zprezto/runcoms/zshrc
    ~/.ideavimrc: ideavimrc
    ~/.tmux/start.sh: tmux/start.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [fc-cache -fv, Installing fonts]
